export const Icons = {
  cancel: require('../../../assets/cancel.png'),
  flag: require('../../../assets/flag.png'),
  pencil: require('../../../assets/pencil.png'),
  check: require('../../../assets/check.png'),
  logo: require('../../../assets/logo.png'),
  map: require('../../../assets/map.png'),
  priceCard: require('../../../assets/priceCard.png'),
  price: require('../../../assets/price.png'),
  sale: require('../../../assets/sale.png'),
  voucher: require('../../../assets/voucher.png'),
  azs: require('../../../assets/azs.png'),
  account: require('../../../assets/account.png'),
  menu: require('../../../assets/menu.png'),
  bell: require('../../../assets/bell.png'),
  rightArrow: require('../../../assets/rightArrow.png'),
  productCode: require('../../../assets/productCode.png'),
};
